#!/bin/sh

. "$(dirname "$0")/.env"

set -e

shutdown() {
    echo -e "\rshutting down..."
    docker compose down > /dev/null 2>&1
    exit 0
}

trap shutdown INT

# install npm modules
[ ! -d "./backend/node_modules" ] && npm i --prefix ./backend > /dev/null
[ ! -d "./frontend/node_modules" ] && npm i --prefix ./frontend > /dev/null

if ! docker volume ls | grep messenger_messengerdb > /dev/null; then
    docker volume create messenger_messengerdb > /dev/null
fi

# spin up database from docker-compose
docker compose up -d postgres --build > /dev/null 2>&1

retries=5
while ! docker exec -it messenger_postgres pg_isready -U $DB_USER > /dev/null 2>&1; do
    retries=$((retries-1))
    if [ $retries -le 0 ]; then
        echo "postgres is not ready, exiting..."
        exit 1
    fi
    sleep 1
done

# Set timezone to UTC for consistency with Docker environment
export TZ=UTC
echo "Setting timezone to UTC for Node.js processes to match Docker environment"

# start backend in dev mode
npm run dev --prefix ./backend &
BACKEND_PID=$!

# start frontend in dev mode
npm run dev --prefix ./frontend &
FRONTEND_PID=$!

echo "running on http://localhost:$FRONTEND_PORT"

wait $BACKEND_PID $FRONTEND_PID
