@baseUrl = http://localhost:3000

### CREATE USER
POST {{baseUrl}}/user
Content-Type: application/json

{
    "username": "johndoe",
    "password": "johndoe"
}

### login as user
# @name login
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "username": "johndoe",
    "password": "johndoe"
}

###
@authToken = {{login.response.body.token}}

### GET USER BY UID
GET {{baseUrl}}/user/1
Authorization: Bearer {{authToken}}

### GET MESSAGES BY SENDER AND RECEIVER UID
GET http://localhost:3000/message?sender_uid=1&receiver_uid=2
Content-Type: application/json

### CONTACT ROUTER TEST CASES

### Get all contacts for user (authorized)
GET {{baseUrl}}/contact/1
Authorization: Bearer {{authToken}}

### Get all contacts for user (unauthorized/wrong user)
GET {{baseUrl}}/contact/2
Authorization: Bearer {{authToken}}

### Get all contacts without authentication
GET {{baseUrl}}/contact/1

### Add new contact
POST {{baseUrl}}/contact/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "contactUserId": 2
}

### Add invalid contact (yourself)
POST {{baseUrl}}/contact/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "contactUserId": 1
}

### Add non-existent contact
POST {{baseUrl}}/contact/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "contactUserId": 999
}

### Add contact (unauthorized)
POST {{baseUrl}}/contact/2
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "contactUserId": 1
}

### Block a contact
PUT {{baseUrl}}/contact/1/2/block
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "blocked": true
}

### Unblock a contact
PUT {{baseUrl}}/contact/1/2/block
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "blocked": false
}

### Block contact with invalid blocked value
PUT {{baseUrl}}/contact/1/2/block
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "blocked": "not-a-boolean"
}

### Block non-existent contact
PUT {{baseUrl}}/contact/1/999/block
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "blocked": true
}

### Delete a contact
DELETE {{baseUrl}}/contact/1/2
Authorization: Bearer {{authToken}}

### Delete non-existent contact
DELETE {{baseUrl}}/contact/1/999
Authorization: Bearer {{authToken}}

### Delete contact (unauthorized)
DELETE {{baseUrl}}/contact/2/1
Authorization: Bearer {{authToken}}

### USER UPDATE AND DELETE TEST CASES

### Update user (authorized) - Change username
PUT {{baseUrl}}/user/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "username": "johndoe_updated"
}

### Update user (authorized) - Change password
PUT {{baseUrl}}/user/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "password": "new_password123"
}

### Update user (authorized) - Change both username and password
PUT {{baseUrl}}/user/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "username": "johndoe_new",
  "password": "secure_password"
}

### Update user without any data to update
PUT {{baseUrl}}/user/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
}

### Delete user (authorized)
DELETE {{baseUrl}}/user/1
Authorization: Bearer {{authToken}}


### Send message 
POST {{baseUrl}}/message
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "sender_uid": 1,
    "receiver_uid": 2,
    "content": "Hello, this is another test message."
}