@startuml Messenger

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

table(User) {
    primary_key(uid) : int
    --
    column(username) : varchar
    column(password_hash) : varchar
    column(created_at) : datetime
}

table(Message) {
    primary_key(mid) : int
    --
    foreign_key(sender_uid) : int
    foreign_key(receiver_uid) : int
    --
    column(content) : varchar
    column(timestamp) : datetime
}

User ||-right-o{ Message : sends
User ||-right-o{ Message : receives

@enduml
